- name: "Status: 🗯️ Waiting for feedback"
  color: "f7d692"
- name: "Status: 🔴 Blocked"
  color: "f7d692"
  description: "Blocked by another issue or pull request"
- name: "Status: 🔒 After next release"
  color: "f7d692"
  description: "Will be done after the next release"

- name: "Closed: ⚰️ Inactive"
  color: "959a9c"
  description: "No answer was received for weeks"
- name: "Closed: 👥 Duplicate"
  color: "959a9c"
  description: "Issue duplicates an existing issue"
- name: "Closed: 🗑️ Bad issue"
  color: "959a9c"

- name: "Priority: 🚨 Urgent"
  color: "03adfc"
- name: "Priority: 💤 Low priority"
  color: "03adfc"

- name: "Complexity: ☣️ Hard to do"
  color: "ff9efc"
- name: "Complexity: 🟩 Easy to do"
  color: "ff9efc"

- name: "Category: Config problem 📝"
  color: "ffc7ea"
- name: "Category: Healthcheck 🩺"
  color: "ffc7ea"
- name: "Category: Documentation ✒️"
  description: "A problem with the readme or in the docs/ directory"
  color: "ffc7ea"
- name: "Category: Maintenance ⛓️"
  description: "Anything related to code or other maintenance"
  color: "ffc7ea"
- name: "Category: Good idea 🎯"
  description: "This is a good idea, judged by the maintainers"
  color: "ffc7ea"
- name: "Category: Motivated! 🙌"
  description: "Your pumpness makes me pumped! The issue or PR shows great motivation!"
  color: "ffc7ea"
- name: "Category: Foolproof settings 👼"
  color: "ffc7ea"
- name: "Category: Label missing ❗"
  color: "ffc7ea"
- name: "Category: Provider update ♻️"
  color: "ffc7ea"
- name: "Category: Shoutrrr 📢"
  color: "ffc7ea"
- name: "Category: IP fetching 📥"
  color: "ffc7ea"
- name: "Category: Database 🗃️"
  color: "ffc7ea"
- name: "Category: New provider 🆕"
  color: "ffc7ea"
- name: "Category: Web UI 🖱️"
  color: "ffc7ea"
- name: "Category: Wildcard 🃏"
  color: "ffc7ea"
