apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddns-updater
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ddns-updater
                port:
                  name: http
