apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml

# this patches the hostname of the Ingress
patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: localhost # add your fqdn
    target:
      kind: Ingress
      name: ddns-updater
